# Generated by Django 6.0.4 on 2026-05-02 20:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OITT',
            fields=[
                ('Code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TreeType', models.CharField(db_index=True, default='P', max_length=1)),
                ('Quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Base quantity (e.g. per 1 finished unit).', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
            ],
            options={
                'verbose_name': 'Bill of materials',
                'verbose_name_plural': 'Bills of materials',
                'db_table': 'OITT',
            },
        ),
        migrations.CreateModel(
            name='OWOR',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Status', models.CharField(db_index=True, default='P', max_length=1)),
                ('PlannedQty', models.DecimalField(decimal_places=6, max_digits=19)),
                ('CmpltQty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('PostDate', models.DateField(db_index=True)),
                ('WhsCode', models.CharField(db_column='Warehouse', db_index=True, max_length=20)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
            ],
            options={
                'verbose_name': 'Production order',
                'verbose_name_plural': 'Production orders',
                'db_table': 'OWOR',
            },
        ),
        migrations.CreateModel(
            name='ITT1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_column='Code', db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('WhsCode', models.CharField(db_column='Warehouse', db_index=True, max_length=20)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
                ('header', models.ForeignKey(db_column='Father', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_production.oitt')),
            ],
            options={
                'verbose_name': 'BOM line',
                'verbose_name_plural': 'BOM lines',
                'db_table': 'ITT1',
                'indexes': [models.Index(fields=['ItemCode'], name='itt1_item_ix')],
            },
        ),
        migrations.CreateModel(
            name='WOR1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('PlannedQty', models.DecimalField(decimal_places=6, max_digits=19)),
                ('IssuedQty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('WhsCode', models.CharField(db_column='wareHouse', db_index=True, max_length=20)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_production.owor')),
            ],
            options={
                'verbose_name': 'Production order line',
                'verbose_name_plural': 'Production order lines',
                'db_table': 'WOR1',
                'indexes': [models.Index(fields=['ItemCode'], name='wor1_item_ix')],
            },
        ),
    ]
