# Generated by Django 5.2.13 on 2026-05-02 21:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itt1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='itt1',
            name='ItemCode',
            field=models.CharField(db_column='Code', db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='itt1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='itt1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='itt1',
            name='WhsCode',
            field=models.CharField(db_column='Warehouse', db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='itt1',
            name='header',
            field=models.ForeignKey(db_column='Father', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_production.oitt', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='oitt',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oitt',
            name='Code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Product No.'),
        ),
        migrations.AlterField(
            model_name='oitt',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Base quantity (e.g. per 1 finished unit).', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Base Quantity'),
        ),
        migrations.AlterField(
            model_name='oitt',
            name='TreeType',
            field=models.CharField(db_index=True, default='P', max_length=1, verbose_name='BOM Category'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='CmpltQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Completed Quantity'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='PlannedQty',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Planned Quantity'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='PostDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='Status',
            field=models.CharField(db_index=True, default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='owor',
            name='WhsCode',
            field=models.CharField(db_column='Warehouse', db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='wor1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='wor1',
            name='IssuedQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Issued Quantity'),
        ),
        migrations.AlterField(
            model_name='wor1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='wor1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='wor1',
            name='PlannedQty',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Planned Quantity'),
        ),
        migrations.AlterField(
            model_name='wor1',
            name='WhsCode',
            field=models.CharField(db_column='wareHouse', db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='wor1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_production.owor', verbose_name='Document'),
        ),
    ]
