# Generated by Django 6.0.4 on 2026-05-02 23:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_production', '0002_alter_itt1_canceled_alter_itt1_itemcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itt1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='itt1',
            name='IssueMeth',
            field=models.CharField(db_index=True, default='M', max_length=1, verbose_name='Issue Method'),
        ),
        migrations.AddField(
            model_name='itt1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AddField(
            model_name='oitt',
            name='Locked',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Locked (BOM)'),
        ),
        migrations.AddField(
            model_name='oitt',
            name='TreeName',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='BOM Display Name'),
        ),
        migrations.AddField(
            model_name='owor',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='owor',
            name='DueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='owor',
            name='OrigEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Origin Entry'),
        ),
        migrations.AddField(
            model_name='owor',
            name='OrigType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Origin Type'),
        ),
        migrations.AddField(
            model_name='owor',
            name='Project',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='wor1',
            name='LineText',
            field=models.TextField(blank=True, default='', verbose_name='Line Text'),
        ),
        migrations.AddField(
            model_name='wor1',
            name='VisOrder',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Visual Order'),
        ),
    ]
