# Generated by Django 6.0.4 on 2026-05-02 19:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ODLN',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
                ('DocDate', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'ODLN',
            },
        ),
        migrations.CreateModel(
            name='OINV',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
                ('DocDate', models.DateField(db_index=True)),
                ('DocTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('VatSum', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name': 'A/R invoice',
                'verbose_name_plural': 'A/R invoices',
                'db_table': 'OINV',
            },
        ),
        migrations.CreateModel(
            name='OQUT',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
                ('DocStatus', models.CharField(db_index=True, default='O', max_length=1)),
                ('DocDate', models.DateField(db_index=True)),
                ('DocTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name': 'Sales quotation',
                'verbose_name_plural': 'Sales quotations',
                'db_table': 'OQUT',
            },
        ),
        migrations.CreateModel(
            name='ORDN',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'db_table': 'ORDN',
            },
        ),
        migrations.CreateModel(
            name='ORDR',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
                ('NumAtCard', models.CharField(blank=True, default='', max_length=100)),
                ('DocStatus', models.CharField(db_index=True, default='O', max_length=1)),
                ('DocDate', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Sales order',
                'verbose_name_plural': 'Sales orders',
                'db_table': 'ORDR',
            },
        ),
        migrations.CreateModel(
            name='DLN1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseLine', models.IntegerField(blank=True, db_index=True, null=True)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.odln')),
            ],
            options={
                'verbose_name': 'Delivery line',
                'verbose_name_plural': 'Delivery lines',
                'db_table': 'DLN1',
                'indexes': [models.Index(fields=['ItemCode'], name='dln1_itemcode_ix'), models.Index(fields=['WhsCode'], name='dln1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='INV1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('LineTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.oinv')),
            ],
            options={
                'verbose_name': 'A/R invoice line',
                'verbose_name_plural': 'A/R invoice lines',
                'db_table': 'INV1',
                'indexes': [models.Index(fields=['ItemCode'], name='inv1_itemcode_ix')],
            },
        ),
        migrations.CreateModel(
            name='QUT1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Dscription', models.CharField(blank=True, default='', max_length=200)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('LineTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.oqut')),
            ],
            options={
                'verbose_name': 'Sales quotation line',
                'verbose_name_plural': 'Sales quotation lines',
                'db_table': 'QUT1',
                'indexes': [models.Index(fields=['ItemCode'], name='qut1_itemcode_ix'), models.Index(fields=['WhsCode'], name='qut1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='RDN1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.ordn')),
            ],
            options={
                'verbose_name': 'Return line',
                'verbose_name_plural': 'Return lines',
                'db_table': 'RDN1',
                'indexes': [models.Index(fields=['ItemCode'], name='rdn1_itemcode_ix'), models.Index(fields=['WhsCode'], name='rdn1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='RDR1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseLine', models.IntegerField(blank=True, db_index=True, null=True)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.ordr')),
            ],
            options={
                'verbose_name': 'Sales order line',
                'verbose_name_plural': 'Sales order lines',
                'db_table': 'RDR1',
                'indexes': [models.Index(fields=['ItemCode'], name='rdr1_itemcode_ix'), models.Index(fields=['WhsCode'], name='rdr1_whscode_ix')],
            },
        ),
    ]
