# Generated by Django 5.2.13 on 2026-05-02 21:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_sales', '0002_sales_soft_delete_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dln1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='dln1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AlterField(
            model_name='dln1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='dln1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='dln1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='dln1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='dln1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dln1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='dln1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.odln', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.oinv', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='odln',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='odln',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='odln',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='odln',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='odln',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='odln',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AlterField(
            model_name='ordn',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='ordn',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='ordn',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='ordn',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='ordn',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.oqut', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='rdn1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='rdn1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='rdn1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='rdn1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='rdn1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='rdn1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='rdn1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.ordn', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_sales.ordr', verbose_name='Document'),
        ),
    ]
