# Generated by Django 5.2.13 on 2026-05-02 22:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_sales', '0003_alter_dln1_baseentry_alter_dln1_baseline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordr',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='rdr1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='rdr1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='rdr1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
    ]
