# Generated by Django 5.2.13 on 2026-05-02 22:53

import datetime

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_sales', '0004_expand_sales_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dln1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='dln1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='dln1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='dln1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AddField(
            model_name='inv1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AddField(
            model_name='inv1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='inv1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='inv1',
            name='WhsCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='odln',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='odln',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='odln',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='odln',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='odln',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='odln',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='odln',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AddField(
            model_name='odln',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='odln',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='odln',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='odln',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='odln',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='DocDate',
            field=models.DateField(db_index=True, default=datetime.date(1970, 1, 1), verbose_name='Posting Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordn',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='qut1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='rdn1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AddField(
            model_name='rdn1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AddField(
            model_name='rdn1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='rdn1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='rdn1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='rdn1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
    ]
