# Generated by Django 6.0.4 on 2026-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_sales', '0005_dln1_discprcnt_dln1_dscription_dln1_linetotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odln',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='odln',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='oinv',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='oqut',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='ordn',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='ordr',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
    ]
