# Generated by Django 5.2.13 on 2026-05-02 22:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OACT',
            fields=[
                ('AcctCode', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, verbose_name='G/L Account')),
                ('AcctName', models.CharField(max_length=200, verbose_name='Account Name')),
                ('CurrTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Balance')),
                ('GroupMask', models.PositiveSmallIntegerField(db_index=True, verbose_name='Account Type')),
                ('FatherNum', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Father Account')),
                ('Postable', models.CharField(db_index=True, default='Y', max_length=1, verbose_name='Posting Allowed')),
                ('LocCash', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Cash Account')),
            ],
            options={
                'verbose_name': 'G/L account',
                'verbose_name_plural': 'Chart of accounts',
                'db_table': 'OACT',
            },
        ),
        migrations.CreateModel(
            name='OFPR',
            fields=[
                ('AbsEntry', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.')),
                ('PeriodCode', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Subperiod Code')),
                ('F_RefDate', models.DateField(verbose_name='Period From')),
                ('T_RefDate', models.DateField(verbose_name='Period To')),
                ('PeriodStat', models.CharField(db_index=True, default='Unlocked', max_length=20, verbose_name='Period Status')),
            ],
            options={
                'verbose_name': 'Financial period',
                'verbose_name_plural': 'Financial periods',
                'db_table': 'OFPR',
            },
        ),
        migrations.CreateModel(
            name='OJDT',
            fields=[
                ('TransId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.')),
                ('BaseRef', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Reference')),
                ('RefDate', models.DateField(db_index=True, verbose_name='Posting Date')),
                ('TransType', models.IntegerField(db_index=True, verbose_name='Transaction Type')),
                ('Memo', models.TextField(blank=True, default='', verbose_name='Memo')),
            ],
            options={
                'verbose_name': 'Journal entry',
                'verbose_name_plural': 'Journal entries',
                'db_table': 'OJDT',
            },
        ),
        migrations.CreateModel(
            name='OPRC',
            fields=[
                ('PrcCode', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, verbose_name='Profit Center')),
                ('PrcName', models.CharField(max_length=200, verbose_name='Profit Center Name')),
                ('DimCode', models.PositiveSmallIntegerField(verbose_name='Dimension No.')),
                ('Active', models.CharField(db_index=True, default='Y', max_length=1, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Profit / cost center',
                'verbose_name_plural': 'Profit / cost centers',
                'db_table': 'OPRC',
            },
        ),
        migrations.CreateModel(
            name='ORCT',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.')),
                ('CardCode', models.CharField(db_index=True, max_length=15, verbose_name='BP Code')),
                ('CardName', models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name')),
                ('DocDate', models.DateField(db_index=True, verbose_name='Posting Date')),
                ('CashAcct', models.CharField(blank=True, default='', max_length=20, verbose_name='Cash Account')),
                ('CheckAcct', models.CharField(blank=True, default='', max_length=20, verbose_name='Check Account')),
                ('DocTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total')),
                ('CashSum', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cash')),
            ],
            options={
                'verbose_name': 'Incoming payment',
                'verbose_name_plural': 'Incoming payments',
                'db_table': 'ORCT',
            },
        ),
        migrations.CreateModel(
            name='OSTC',
            fields=[
                ('Code', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, verbose_name='Code')),
                ('Name', models.CharField(max_length=200, verbose_name='Name')),
                ('Rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Rate')),
                ('Account', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Tax Account')),
            ],
            options={
                'verbose_name': 'Tax code',
                'verbose_name_plural': 'Tax codes',
                'db_table': 'OSTC',
            },
        ),
        migrations.CreateModel(
            name='OVPM',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.')),
                ('CardCode', models.CharField(db_index=True, max_length=15, verbose_name='BP Code')),
                ('CardName', models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name')),
                ('DocDate', models.DateField(db_index=True, verbose_name='Posting Date')),
                ('BankAcct', models.CharField(blank=True, default='', max_length=20, verbose_name='Bank Account')),
                ('CashSum', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cash')),
                ('TrsfrSum', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bank Transfer')),
                ('DocTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total')),
            ],
            options={
                'verbose_name': 'Outgoing payment',
                'verbose_name_plural': 'Outgoing payments',
                'db_table': 'OVPM',
            },
        ),
        migrations.CreateModel(
            name='OBGT',
            fields=[
                ('AcctCode', models.OneToOneField(db_column='AcctCode', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='budget', serialize=False, to='tenant_finance.oact', verbose_name='G/L Account')),
                ('BudgTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Budget Total')),
            ],
            options={
                'verbose_name': 'Budget setup',
                'verbose_name_plural': 'Budget setups',
                'db_table': 'OBGT',
            },
        ),
        migrations.CreateModel(
            name='JDT1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'Line_ID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Line_ID', models.IntegerField(db_column='Line_ID', verbose_name='Line ID')),
                ('Account', models.CharField(db_index=True, max_length=20, verbose_name='G/L Account')),
                ('ShortName', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Short Name')),
                ('Debit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Debit')),
                ('Credit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Credit')),
                ('ProfitCode', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Profit Center')),
                ('header', models.ForeignKey(db_column='TransId', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_finance.ojdt', verbose_name='Journal entry')),
            ],
            options={
                'verbose_name': 'Journal entry line',
                'verbose_name_plural': 'Journal entry lines',
                'db_table': 'JDT1',
            },
        ),
        migrations.CreateModel(
            name='RCT1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField(verbose_name='Line No.')),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.')),
                ('SumApplied', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Applied Amount')),
                ('InvType', models.IntegerField(db_index=True, default=0, verbose_name='Invoice Type')),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_finance.orct', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Incoming payment line',
                'verbose_name_plural': 'Incoming payment lines',
                'db_table': 'RCT1',
            },
        ),
        migrations.CreateModel(
            name='VPM1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField(verbose_name='Line No.')),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.')),
                ('SumApplied', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Applied Amount')),
                ('InvType', models.IntegerField(db_index=True, default=0, verbose_name='Invoice Type')),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_finance.ovpm', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Outgoing payment line',
                'verbose_name_plural': 'Outgoing payment lines',
                'db_table': 'VPM1',
            },
        ),
        migrations.CreateModel(
            name='BGT1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'Month', 'PrcCode', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month')),
                ('PrcCode', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Profit Center')),
                ('PlannedAmt', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Planned Amount')),
                ('header', models.ForeignKey(db_column='AcctCode', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_finance.obgt', verbose_name='G/L Account')),
            ],
            options={
                'verbose_name': 'Budget line',
                'verbose_name_plural': 'Budget lines',
                'db_table': 'BGT1',
            },
        ),
    ]
