# Generated by Django 6.0.4 on 2026-05-02 23:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdt1',
            name='DueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date (line)'),
        ),
        migrations.AddField(
            model_name='jdt1',
            name='LineMemo',
            field=models.TextField(blank=True, default='', verbose_name='Line memo'),
        ),
        migrations.AddField(
            model_name='jdt1',
            name='OcrCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=11, verbose_name='Offset Account'),
        ),
        migrations.AddField(
            model_name='jdt1',
            name='Ref1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Reference 1'),
        ),
        migrations.AddField(
            model_name='jdt1',
            name='Ref2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Reference 2'),
        ),
        migrations.AddField(
            model_name='jdt1',
            name='Ref3Line',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Reference 3 (line)'),
        ),
        migrations.AddField(
            model_name='jdt1',
            name='VatGroup',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8, verbose_name='VAT Group (Sales)'),
        ),
        migrations.AddField(
            model_name='oact',
            name='AcctFixed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Fixed Asset Account'),
        ),
        migrations.AddField(
            model_name='oact',
            name='ExportCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Export Code'),
        ),
        migrations.AddField(
            model_name='oact',
            name='Frozen',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Frozen'),
        ),
        migrations.AddField(
            model_name='oact',
            name='Levels',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Account Levels'),
        ),
        migrations.AddField(
            model_name='oact',
            name='ValidFor',
            field=models.CharField(db_index=True, default='Y', max_length=1, verbose_name='Valid For'),
        ),
        migrations.AddField(
            model_name='ojdt',
            name='DueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date (header)'),
        ),
        migrations.AddField(
            model_name='ojdt',
            name='Project',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='ojdt',
            name='Ref1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Reference 1'),
        ),
        migrations.AddField(
            model_name='ojdt',
            name='Ref2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Reference 2'),
        ),
        migrations.AddField(
            model_name='ojdt',
            name='TransCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Transaction Code'),
        ),
        migrations.AddField(
            model_name='oprc',
            name='PrcFather',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Father Center'),
        ),
        migrations.AddField(
            model_name='orct',
            name='CheckSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Check Amount'),
        ),
        migrations.AddField(
            model_name='orct',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='orct',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Document Status'),
        ),
        migrations.AddField(
            model_name='orct',
            name='JrnlMemo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='orct',
            name='TrsfrAcct',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Transfer Account'),
        ),
        migrations.AddField(
            model_name='ostc',
            name='Frozen',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Frozen'),
        ),
        migrations.AddField(
            model_name='ostc',
            name='ValidFor',
            field=models.CharField(db_index=True, default='Y', max_length=1, verbose_name='Valid For'),
        ),
        migrations.AddField(
            model_name='ovpm',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='ovpm',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Document Status'),
        ),
        migrations.AddField(
            model_name='ovpm',
            name='JrnlMemo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='ovpm',
            name='TrsfrAcct',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Transfer Account'),
        ),
    ]
