# Generated by Django 6.0.4 on 2026-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0003_sap_stub_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='oact',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='oact',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='ojdt',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='ojdt',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='oprc',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='oprc',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='orct',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='orct',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='ovpm',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='ovpm',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
    ]
