# Generated by Django 6.0.4 on 2026-05-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OWHS',
            fields=[
                ('WhsCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('WhsName', models.CharField(db_index=True, max_length=200)),
                ('Location', models.CharField(blank=True, default='', max_length=100)),
                ('Inactive', models.CharField(db_index=True, default='N', max_length=1)),
            ],
            options={
                'db_table': 'OWHS',
                'indexes': [models.Index(fields=['WhsCode'], name='owhs_whscode_ix')],
            },
        ),
    ]
