# Generated by Django 6.0.4 on 2026-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owhs',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterField(
            model_name='owhs',
            name='Inactive',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Inactive (Y/N)'),
        ),
        migrations.AlterField(
            model_name='owhs',
            name='Location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='owhs',
            name='WhsCode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Warehouse code'),
        ),
        migrations.AlterField(
            model_name='owhs',
            name='WhsName',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Warehouse name'),
        ),
    ]
