# Generated by Django 5.2.13 on 2026-05-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_warehouse', '0002_alter_owhs_options_alter_owhs_inactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owhs',
            name='Inactive',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Inactive'),
        ),
        migrations.AlterField(
            model_name='owhs',
            name='WhsCode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Warehouse Code'),
        ),
        migrations.AlterField(
            model_name='owhs',
            name='WhsName',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Warehouse Name'),
        ),
    ]
