# Generated by Django 6.0.4 on 2026-05-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_warehouse', '0003_alter_owhs_inactive_alter_owhs_whscode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owhs',
            name='BinActivat',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Bin Locations Active'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='Block',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='Building',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='City',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='Country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='County',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='County / District'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='DropShip',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Drop Ship'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='E_Mail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='Fax',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='FederalTaxID',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Federal Tax ID'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='Locked',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Locked (warehouse)'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='Phone1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone 1'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='Phone2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='State',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='State / Region'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='Street',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='StreetNo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Street No.'),
        ),
        migrations.AddField(
            model_name='owhs',
            name='ZipCode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Zip Code'),
        ),
    ]
