# Generated by Django 6.0.4 on 2026-05-02 19:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OIGE',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('DocDate', models.DateField(db_index=True)),
                ('Comments', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'OIGE',
            },
        ),
        migrations.CreateModel(
            name='OIGN',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('DocDate', models.DateField(db_index=True)),
                ('Comments', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'OIGN',
            },
        ),
        migrations.CreateModel(
            name='OINC',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CountDate', models.DateField(db_index=True)),
            ],
            options={
                'db_table': 'OINC',
            },
        ),
        migrations.CreateModel(
            name='OITB',
            fields=[
                ('ItmsGrpCod', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ItmsGrpNam', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'OITB',
            },
        ),
        migrations.CreateModel(
            name='OITW',
            fields=[
                ('pk', models.CompositePrimaryKey('ItemCode', 'WhsCode', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('OnHand', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('IsCommited', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('AvgPrice', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'db_table': 'OITW',
            },
        ),
        migrations.CreateModel(
            name='OWTR',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('DocDate', models.DateField(db_index=True)),
                ('Filler', models.CharField(db_index=True, max_length=20)),
                ('Comments', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'OWTR',
            },
        ),
        migrations.CreateModel(
            name='OINM',
            fields=[
                ('TransNum', models.BigAutoField(primary_key=True, serialize=False)),
                ('TransType', models.IntegerField(db_index=True)),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Warehouse', models.CharField(db_index=True, max_length=20)),
                ('InQty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('OutQty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('BASE_REF', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('DocTime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'OINM',
                'indexes': [models.Index(fields=['ItemCode', 'Warehouse'], name='oinm_item_wh_ix')],
            },
        ),
        migrations.CreateModel(
            name='OITM',
            fields=[
                ('ItemCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ItemName', models.CharField(db_index=True, max_length=200)),
                ('InvntItem', models.CharField(db_index=True, default='Y', max_length=1)),
                ('OnHand', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('IsCommited', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('OnOrder', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ByWh', models.CharField(db_index=True, default='N', max_length=1)),
                ('ItmsGrpCod', models.ForeignKey(db_column='ItmsGrpCod', on_delete=django.db.models.deletion.PROTECT, related_name='oitm_set', to='tenant_inventory.oitb')),
            ],
            options={
                'db_table': 'OITM',
            },
        ),
        migrations.CreateModel(
            name='IGE1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('Account', models.CharField(blank=True, default='', max_length=20)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.oige')),
            ],
            options={
                'db_table': 'IGE1',
                'indexes': [models.Index(fields=['ItemCode'], name='ige1_itemcode_ix'), models.Index(fields=['WhsCode'], name='ige1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='IGN1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.oign')),
            ],
            options={
                'db_table': 'IGN1',
                'indexes': [models.Index(fields=['ItemCode'], name='ign1_itemcode_ix'), models.Index(fields=['WhsCode'], name='ign1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='INC1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('InQty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('OutQty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('Difference', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.oinc')),
            ],
            options={
                'db_table': 'INC1',
                'indexes': [models.Index(fields=['ItemCode'], name='inc1_itemcode_ix'), models.Index(fields=['WhsCode'], name='inc1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='WTR1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.owtr')),
            ],
            options={
                'db_table': 'WTR1',
                'indexes': [models.Index(fields=['ItemCode'], name='wtr1_itemcode_ix'), models.Index(fields=['WhsCode'], name='wtr1_whscode_ix')],
            },
        ),
    ]
