# Generated by Django 6.0.4 on 2026-05-02 19:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OUOM',
            fields=[
                ('UomEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('UomCode', models.CharField(db_index=True, max_length=20, unique=True)),
                ('UomName', models.CharField(db_index=True, max_length=100)),
                ('Locked', models.CharField(db_index=True, default='N', max_length=1)),
                ('DataSource', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'OUOM',
            },
        ),
        migrations.CreateModel(
            name='OWTQ',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('DocDate', models.DateField(db_index=True)),
                ('Filler', models.CharField(db_index=True, max_length=8)),
                ('Comments', models.CharField(blank=True, default='', max_length=254)),
            ],
            options={
                'db_table': 'OWTQ',
            },
        ),
        migrations.CreateModel(
            name='WTQ1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('OpenQty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('FromWhsCod', models.CharField(db_index=True, max_length=8)),
                ('WhsCode', models.CharField(db_index=True, max_length=8)),
                ('LineStatus', models.CharField(db_index=True, default='O', max_length=1)),
                ('TargetType', models.IntegerField(default=-1)),
                ('TrgetEntry', models.IntegerField(blank=True, null=True)),
                ('BaseRef', models.CharField(blank=True, default='', max_length=16)),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.owtq')),
            ],
            options={
                'db_table': 'WTQ1',
                'indexes': [models.Index(fields=['ItemCode'], name='wtq1_itemcode_ix'), models.Index(fields=['FromWhsCod'], name='wtq1_fromwhs_ix'), models.Index(fields=['WhsCode'], name='wtq1_whscode_ix')],
            },
        ),
    ]
