# Generated by Django 6.0.4 on 2026-05-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventory', '0002_ouom_owtq_wtq1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ige1',
            options={'verbose_name': 'Goods issue line', 'verbose_name_plural': 'Goods issue lines'},
        ),
        migrations.AlterModelOptions(
            name='ign1',
            options={'verbose_name': 'Goods receipt line', 'verbose_name_plural': 'Goods receipt lines'},
        ),
        migrations.AlterModelOptions(
            name='inc1',
            options={'verbose_name': 'Inventory posting line', 'verbose_name_plural': 'Inventory posting lines'},
        ),
        migrations.AlterModelOptions(
            name='oige',
            options={'verbose_name': 'Goods issue', 'verbose_name_plural': 'Goods issues'},
        ),
        migrations.AlterModelOptions(
            name='oign',
            options={'verbose_name': 'Goods receipt', 'verbose_name_plural': 'Goods receipts'},
        ),
        migrations.AlterModelOptions(
            name='oinc',
            options={'verbose_name': 'Inventory posting', 'verbose_name_plural': 'Inventory postings'},
        ),
        migrations.AlterModelOptions(
            name='oinm',
            options={'verbose_name': 'Inventory transaction log', 'verbose_name_plural': 'Inventory transaction log'},
        ),
        migrations.AlterModelOptions(
            name='oitb',
            options={'verbose_name': 'Item group', 'verbose_name_plural': 'Item groups'},
        ),
        migrations.AlterModelOptions(
            name='oitm',
            options={'verbose_name': 'Item master', 'verbose_name_plural': 'Item master data'},
        ),
        migrations.AlterModelOptions(
            name='oitw',
            options={'verbose_name': 'Item warehouse stock', 'verbose_name_plural': 'Item warehouse stock'},
        ),
        migrations.AlterModelOptions(
            name='ouom',
            options={'verbose_name': 'Unit of measure', 'verbose_name_plural': 'Units of measure'},
        ),
        migrations.AlterModelOptions(
            name='owtq',
            options={'verbose_name': 'Inventory transfer request', 'verbose_name_plural': 'Inventory transfer requests'},
        ),
        migrations.AlterModelOptions(
            name='owtr',
            options={'verbose_name': 'Inventory transfer', 'verbose_name_plural': 'Inventory transfers'},
        ),
        migrations.AlterModelOptions(
            name='wtq1',
            options={'verbose_name': 'Inventory transfer request line', 'verbose_name_plural': 'Inventory transfer request lines'},
        ),
        migrations.AlterModelOptions(
            name='wtr1',
            options={'verbose_name': 'Inventory transfer line', 'verbose_name_plural': 'Inventory transfer lines'},
        ),
    ]
