# Generated by Django 6.0.4 on 2026-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventory', '0004_inventory_soft_delete_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ige1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ign1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
