# Generated by Django 5.2.13 on 2026-05-02 21:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventory', '0005_ige1_ign1_baseline_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ige1',
            name='Account',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='G/L Account'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='ige1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.oige', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='ign1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.oign', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='Difference',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Difference'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='InQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='In Quantity'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='OutQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Out Quantity'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='inc1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.oinc', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='oige',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oige',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='oige',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='oige',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='oige',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='oign',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oign',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='oign',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='oign',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='oign',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='oinc',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oinc',
            name='CountDate',
            field=models.DateField(db_index=True, verbose_name='Count Date'),
        ),
        migrations.AlterField(
            model_name='oinc',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='oinc',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='BASE_REF',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='User Reference'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='DocTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Posting Date and Time'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='InQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='In Quantity'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='OutQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Out Quantity'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='TransNum',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Transaction No.'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='TransType',
            field=models.IntegerField(db_index=True, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='oinm',
            name='Warehouse',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='oitb',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oitb',
            name='ItmsGrpCod',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Item Group'),
        ),
        migrations.AlterField(
            model_name='oitb',
            name='ItmsGrpNam',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Item Group Name'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='ByWh',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Manage Item by Warehouse'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='InvntItem',
            field=models.CharField(db_index=True, default='Y', max_length=1, verbose_name='Inventory Item'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='IsCommited',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Committed'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='ItemCode',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='ItemName',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='ItmsGrpCod',
            field=models.ForeignKey(db_column='ItmsGrpCod', on_delete=django.db.models.deletion.PROTECT, related_name='oitm_set', to='tenant_inventory.oitb', verbose_name='Item Group'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='OnHand',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='In Stock'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='OnOrder',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ordered'),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='ValidFor',
            field=models.CharField(db_index=True, default='Y', max_length=1, verbose_name='Valid For'),
        ),
        migrations.AlterField(
            model_name='oitw',
            name='AvgPrice',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Avg. Price'),
        ),
        migrations.AlterField(
            model_name='oitw',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oitw',
            name='IsCommited',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Committed'),
        ),
        migrations.AlterField(
            model_name='oitw',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='oitw',
            name='OnHand',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='In Stock'),
        ),
        migrations.AlterField(
            model_name='oitw',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='ouom',
            name='DataSource',
            field=models.CharField(default='N', max_length=1, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='ouom',
            name='Locked',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='ouom',
            name='UomCode',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='UoM Code'),
        ),
        migrations.AlterField(
            model_name='ouom',
            name='UomEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='UoM Entry'),
        ),
        migrations.AlterField(
            model_name='ouom',
            name='UomName',
            field=models.CharField(db_index=True, max_length=100, verbose_name='UoM Name'),
        ),
        migrations.AlterField(
            model_name='owtq',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='owtq',
            name='Comments',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='owtq',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='owtq',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='owtq',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='owtq',
            name='Filler',
            field=models.CharField(db_index=True, max_length=8, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='owtr',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='owtr',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='owtr',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='owtr',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='owtr',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='owtr',
            name='Filler',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='BaseRef',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='FromWhsCod',
            field=models.CharField(db_index=True, max_length=8, verbose_name='From Warehouse'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='LineStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Line Status'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='TargetType',
            field=models.IntegerField(default=-1, verbose_name='Target Type'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='TrgetEntry',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Document'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=8, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='wtq1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.owtq', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='wtr1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='wtr1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='wtr1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='wtr1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='wtr1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='wtr1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='wtr1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_inventory.owtr', verbose_name='Document'),
        ),
    ]
