# Generated by Django 5.2.13 on 2026-05-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventory', '0007_expand_inventory_b1_fields'),
        ('tenant_inventory', '0007_oige_jrnlmemo_oign_jrnlmemo_oitm_buyunitmsr_and_more'),
    ]

    operations = [
    ]
