# Generated by Django 6.0.4 on 2026-05-02 23:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventory', '0008_merge_20260503_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='ige1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='ige1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='ige1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='ige1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='ige1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AddField(
            model_name='ige1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Sales)'),
        ),
        migrations.AddField(
            model_name='ign1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='ign1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='ign1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='ign1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='ign1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AddField(
            model_name='ign1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Sales)'),
        ),
        migrations.AddField(
            model_name='inc1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='oige',
            name='CardCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='BP Code'),
        ),
        migrations.AddField(
            model_name='oige',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AddField(
            model_name='oige',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='oige',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='oige',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='oige',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='oige',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='oige',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='oige',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='oige',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='oige',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='oige',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='oige',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='oige',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='oige',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='oign',
            name='CardCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='BP Code'),
        ),
        migrations.AddField(
            model_name='oign',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AddField(
            model_name='oign',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='oign',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='oign',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='oign',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='oign',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='oign',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='oign',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='oign',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='oign',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='oign',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='oign',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='oign',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='oign',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='CardCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='BP Code'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='JrnlMemo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='oinm',
            name='CreatedBy',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='oinm',
            name='DocEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Linked document entry'),
        ),
        migrations.AddField(
            model_name='oinm',
            name='DocLineNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Linked document line'),
        ),
        migrations.AddField(
            model_name='oinm',
            name='TransValue',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Transaction value'),
        ),
        migrations.AddField(
            model_name='oitb',
            name='Locked',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Locked (item group)'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='Frozen',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Frozen'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='GrsWeight',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gross Weight'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='IUoMEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='IUoM Entry'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='PUoMEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='PUoM Entry'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='PicturName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='SWW',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Warranty Template'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='ValidFrom',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid from'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='ValidTo',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid to'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='VatGourpSa',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8, verbose_name='VAT Group (Sales)'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='VatGroupPu',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8, verbose_name='VAT Group (Purchase)'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='Volume',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='oitm',
            name='Weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='CardCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='BP Code'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='CardCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='BP Code'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='wtq1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='wtq1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='wtq1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='wtq1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='wtq1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Sales)'),
        ),
        migrations.AddField(
            model_name='wtr1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='wtr1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='wtr1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='wtr1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='wtr1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AddField(
            model_name='wtr1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Sales)'),
        ),
    ]
