# Generated by Django 6.0.4 on 2026-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventory', '0009_b1_field_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='oige',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='oige',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='oign',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='oign',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='oinc',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='oinm',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='oinm',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='owtq',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='U_UserFld1',
            field=models.CharField(blank=True, db_column='U_UserFld1', default='', max_length=254, verbose_name='User-defined field 1'),
        ),
        migrations.AddField(
            model_name='owtr',
            name='U_UserFld2',
            field=models.CharField(blank=True, db_column='U_UserFld2', default='', max_length=254, verbose_name='User-defined field 2'),
        ),
    ]
