# Generated by Django 6.0.4 on 2026-05-04 08:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_businesspartner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crd1',
            options={'verbose_name': 'BP address', 'verbose_name_plural': 'BP addresses'},
        ),
        migrations.AlterModelOptions(
            name='ocrd',
            options={'verbose_name': 'Business partner', 'verbose_name_plural': 'Business partners'},
        ),
        migrations.AlterModelOptions(
            name='ocrg',
            options={'verbose_name': 'BP group', 'verbose_name_plural': 'BP groups'},
        ),
        migrations.AlterField(
            model_name='crd1',
            name='Address',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Address ID'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='AdresType',
            field=models.CharField(db_index=True, default='S', max_length=1, verbose_name='Address Type'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='Block',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='Building',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='City',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='Country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='County',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='County / District'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='State',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='State / Region'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='Street',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='ZipCode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='crd1',
            name='header',
            field=models.ForeignKey(db_column='CardCode', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='tenant_businesspartner.ocrd', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Current Account Balance'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='BillToDef',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Default Bill-To'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CardCode',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CardFName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Foreign Name'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CardName',
            field=models.CharField(db_index=True, max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CardType',
            field=models.CharField(db_index=True, default='C', max_length=1, verbose_name='BP Type'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Cellular',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cellular'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CreditLine',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Currency',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='DNotesBal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Deliveries Balance'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='DebtLine',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Debt Limit'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='DfltWhs',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Default Warehouse'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='E_Mail',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Fax',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Frozen',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Frozen'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='GroupCode',
            field=models.ForeignKey(blank=True, db_column='GroupCode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='tenant_businesspartner.ocrg', verbose_name='BP Group'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='LicTradNum',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='OrdersBal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Orders Balance'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='PayTermsGrpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Payment Terms Group'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Phone1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone 1'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Phone2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone 2'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='ShipToDef',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Default Ship-To'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='ValidFor',
            field=models.CharField(db_index=True, default='Y', max_length=1, verbose_name='Valid For'),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='Website',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='ocrg',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='ocrg',
            name='GroupCode',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='BP Group'),
        ),
        migrations.AlterField(
            model_name='ocrg',
            name='GroupName',
            field=models.CharField(db_index=True, max_length=100, verbose_name='BP Group Name'),
        ),
        migrations.AlterField(
            model_name='ocrg',
            name='GroupType',
            field=models.CharField(db_index=True, default='B', max_length=1, verbose_name='Group Type'),
        ),
    ]
