import type { InvRegistryEntry } from "../../inventory/registry";
import { BUSINESS_PARTNER_API_ROOT } from "../constants";

function enc(s: string): string {
  return encodeURIComponent(s);
}

/** Workspace / URL segment: ``/finance/business-partner`` */
export const FINANCE_BUSINESS_PARTNER_MODULE_ID = "business-partner" as const;

export const businessPartnerRegistryEntry: InvRegistryEntry = {
  id: FINANCE_BUSINESS_PARTNER_MODULE_ID,
  title: "Business Partner — OCRD",
  listPath: BUSINESS_PARTNER_API_ROOT,
  detailPath: (r) => `${BUSINESS_PARTNER_API_ROOT}/${enc(String(r.CardCode ?? "").trim())}`,
  pkKeys: ["CardCode"],
  formFirstListOnFind: true,
  readonlyEnv: "finance",
  listColumns: [
    { key: "CardCode", label: "Card Code" },
    { key: "CardName", label: "Card Name" },
    { key: "CardType", label: "Type" },
    { key: "GroupCode", label: "Group" },
    { key: "Currency", label: "Currency" },
    { key: "Balance", label: "Balance" },
    { key: "ValidFor", label: "Valid" },
    { key: "Frozen", label: "Frozen" },
  ],
  headerFields: [
    { key: "CardCode", label: "Card Code", kind: "text", pk: true },
    { key: "CardName", label: "Card Name", kind: "text" },
    { key: "CardType", label: "Card Type (C/S/L)", kind: "text" },
    { key: "GroupCode", label: "BP Group", kind: "number" },
    { key: "CardFName", label: "Foreign Name", kind: "text" },
    { key: "CntctPrsn", label: "Contact Person", kind: "text" },
    { key: "Phone1", label: "Phone 1", kind: "text" },
    { key: "Phone2", label: "Phone 2", kind: "text" },
    { key: "Fax", label: "Fax", kind: "text" },
    { key: "Cellular", label: "Mobile", kind: "text" },
    { key: "E_Mail", label: "E-Mail", kind: "text" },
    { key: "Website", label: "Website", kind: "text" },
    { key: "LicTradNum", label: "Tax ID", kind: "text" },
    { key: "CreditLine", label: "Credit Line", kind: "text" },
    { key: "DebtLine", label: "Debt Line", kind: "text" },
    { key: "Balance", label: "Balance", kind: "text" },
    { key: "OrdersBal", label: "Orders Balance", kind: "text" },
    { key: "DNotesBal", label: "DNotes Balance", kind: "text" },
    { key: "Currency", label: "Currency", kind: "text" },
    { key: "PayTermsGrpCode", label: "Payment Terms Grp", kind: "number" },
    { key: "DfltWhs", label: "Default Whs", kind: "text" },
    { key: "ShipToDef", label: "Ship-To Default", kind: "text" },
    { key: "BillToDef", label: "Bill-To Default", kind: "text" },
    { key: "SlpCode", label: "Sales Employee", kind: "number" },
    { key: "Comments", label: "Comments", kind: "text" },
    { key: "ValidFor", label: "Valid (Y/N)", kind: "text" },
    { key: "Frozen", label: "Frozen (Y/N)", kind: "text" },
    { key: "Canceled", label: "Canceled (Y/N)", kind: "text" },
  ],
  createKeys: [
    "CardCode",
    "CardName",
    "CardType",
    "GroupCode",
    "CardFName",
    "CntctPrsn",
    "Phone1",
    "Phone2",
    "Fax",
    "Cellular",
    "E_Mail",
    "Website",
    "LicTradNum",
    "CreditLine",
    "DebtLine",
    "Balance",
    "OrdersBal",
    "DNotesBal",
    "Currency",
    "PayTermsGrpCode",
    "DfltWhs",
    "ShipToDef",
    "BillToDef",
    "SlpCode",
    "Comments",
  ],
  patchKeys: [
    "CardName",
    "CardType",
    "GroupCode",
    "CardFName",
    "CntctPrsn",
    "Phone1",
    "Phone2",
    "Fax",
    "Cellular",
    "E_Mail",
    "Website",
    "LicTradNum",
    "CreditLine",
    "DebtLine",
    "Balance",
    "OrdersBal",
    "DNotesBal",
    "Currency",
    "PayTermsGrpCode",
    "DfltWhs",
    "ShipToDef",
    "BillToDef",
    "SlpCode",
    "Comments",
    "ValidFor",
    "Frozen",
    "Canceled",
  ],
};
