"""
SAP Business One–style **human-readable** field labels for Django ``verbose_name``.

Technical DB / model attribute names stay SAP-style (e.g. ``ItemCode``, ``Dscription``);
these strings match how the B1 client presents fields in forms (Title Case, readable).

All values use ``gettext_lazy`` so admin and forms respect translations.
"""

from __future__ import annotations

from django.utils.translation import gettext_lazy as _

# --- Document headers ---
INTERNAL_NO = _("Internal No.")
DOCUMENT_NO = _("No.")
BP_CODE = _("BP Code")
BP_NAME = _("BP Name")
STATUS = _("Status")
POSTING_DATE = _("Posting Date")
DOCUMENT_DATE = _("Document Date")
DUE_DATE = _("Due Date")
DELIVERY_DATE = _("Delivery Date")
DOCUMENT_TOTAL = _("Document Total")
TAX = _("Tax")
DISCOUNT_TOTAL = _("Discount Total")
BP_REFERENCE_NO = _("BP Reference No.")
CONTACT_PERSON = _("Contact Person")
CURRENCY = _("Currency")
REMARKS = _("Remarks")
COMMENTS = _("Comments")
SALES_EMPLOYEE = _("Sales Employee")
OWNER = _("Owner")
CREATED_BY = _("Created By")
REQUESTER = _("Requester")
CANCELED = _("Canceled")
VALID_FOR = _("Valid For")

# --- Document lines ---
PARENT_DOCUMENT = _("Document")
LINE_NO = _("Line No.")
ITEM_CODE = _("Item Code")
ITEM_NAME = _("Item Name")
ITEM_DESCRIPTION = _("Item Description")
QUANTITY = _("Quantity")
UNIT_PRICE = _("Unit Price")
WAREHOUSE = _("Warehouse")
FROM_WAREHOUSE = _("From Warehouse")
LINE_STATUS = _("Line Status")
OPEN_QUANTITY = _("Open Quantity")
LINE_TOTAL = _("Line Total")
DISCOUNT_PCT = _("Discount %")
BASE_TYPE = _("Base Type")
BASE_ENTRY = _("Base Entry")
BASE_LINE = _("Base Row")
TARGET_TYPE = _("Target Type")
TARGET_ENTRY = _("Target Document")
REFERENCE = _("Reference")
GL_ACCOUNT = _("G/L Account")

# --- Item groups & item master ---
ITEM_GROUP = _("Item Group")
ITEM_GROUP_NAME = _("Item Group Name")
INVENTORY_ITEM = _("Inventory Item")
IN_STOCK = _("In Stock")
COMMITTED = _("Committed")
ORDERED = _("Ordered")
MANAGE_BY_WAREHOUSE = _("Manage Item by Warehouse")
DEFAULT_WAREHOUSE = _("Default Warehouse")
FOREIGN_NAME = _("Foreign Name")
BARCODE = _("Bar Code")
SALES_ITEM = _("Sales Item")
PURCHASE_ITEM = _("Purchase Item")
SALES_UOM = _("Sales UoM")
PURCHASE_UOM = _("Purchasing UoM")
AVG_PRICE = _("Avg. Price")
ORDER_QTY = _("Ordered (Warehouse)")
MIN_STOCK = _("Minimum Stock")
MAX_STOCK = _("Maximum Stock")
WAREHOUSE_ROW_LOCKED = _("Locked (Warehouse Row)")

# --- UoM ---
UOM_ENTRY = _("UoM Entry")
UOM_CODE = _("UoM Code")
UOM_NAME = _("UoM Name")
LOCKED = _("Locked")
DATA_SOURCE = _("Data Source")

# --- Warehouse (OWHS) ---
WAREHOUSE_CODE = _("Warehouse Code")
WAREHOUSE_NAME = _("Warehouse Name")
LOCATION = _("Location")
INACTIVE = _("Inactive")

# --- Inventory posting / ledger ---
COUNT_DATE = _("Count Date")
IN_QUANTITY = _("In Quantity")
OUT_QUANTITY = _("Out Quantity")
DIFFERENCE = _("Difference")
USER_REFERENCE = _("User Reference")
POSTING_DATE_TIME = _("Posting Date and Time")
TRANSACTION_TYPE = _("Transaction Type")
TRANSACTION_NO = _("Transaction No.")

# --- Production ---
PRODUCT_NO = _("Product No.")
BOM_CATEGORY = _("BOM Category")
BASE_QUANTITY = _("Base Quantity")
PRODUCTION_STATUS = _("Status")
PLANNED_QTY = _("Planned Quantity")
COMPLETED_QTY = _("Completed Quantity")
ISSUED_QTY = _("Issued Quantity")

# --- Finance: chart & dimensions ---
ACCOUNT_CODE = _("G/L Account")
ACCOUNT_NAME = _("Account Name")
BALANCE = _("Balance")
ACCOUNT_TYPE = _("Account Type")
FATHER_ACCOUNT = _("Father Account")
POSTING_ALLOWED = _("Posting Allowed")
CASH_ACCOUNT = _("Cash Account")
CASH_ACCOUNT_FLAG = _("Cash Account")
PROFIT_CENTER = _("Profit Center")
PROFIT_CENTER_NAME = _("Profit Center Name")
DIMENSION_NO = _("Dimension No.")
ACTIVE = _("Active")

# --- Journal ---
JOURNAL_MEMO = _("Memo")
JOURNAL_LINE_ID = _("Line ID")
SHORT_NAME = _("Short Name")
DEBIT = _("Debit")
CREDIT = _("Credit")
PROFIT_CENTER_CODE = _("Profit Center")

# --- Payments ---
CHECK_ACCOUNT = _("Check Account")
CASH_AMOUNT = _("Cash")
BANK_ACCOUNT = _("Bank Account")
BANK_TRANSFER = _("Bank Transfer")
APPLIED_AMOUNT = _("Applied Amount")
INVOICE_TYPE = _("Invoice Type")

# --- Tax (OSTC) ---
CODE = _("Code")
NAME = _("Name")
RATE = _("Rate")
TAX_ACCOUNT = _("Tax Account")

# --- Periods & budget ---
SUBPERIOD_CODE = _("Subperiod Code")
PERIOD_FROM = _("Period From")
PERIOD_TO = _("Period To")
PERIOD_STATUS = _("Period Status")
BUDGET_TOTAL = _("Budget Total")
MONTH = _("Month")
PLANNED_AMOUNT = _("Planned Amount")

# --- Business partner (OCRG, OCRD, CRD1) ---
BP_TYPE = _("BP Type")
BP_GROUP = _("BP Group")
BP_GROUP_NAME = _("BP Group Name")
GROUP_TYPE = _("Group Type")
PHONE_1 = _("Phone 1")
PHONE_2 = _("Phone 2")
FAX = _("Fax")
CELLULAR = _("Cellular")
EMAIL = _("E-Mail")
WEBSITE = _("Website")
TAX_ID = _("Tax ID")
CREDIT_LIMIT = _("Credit Limit")
DEBT_LIMIT = _("Debt Limit")
CURRENT_BALANCE = _("Current Account Balance")
OPEN_ORDERS_BALANCE = _("Open Orders Balance")
OPEN_DELIVERIES_BALANCE = _("Open Deliveries Balance")
PAYMENT_TERMS_GROUP = _("Payment Terms Group")
SHIP_TO_DEFAULT = _("Default Ship-To")
BILL_TO_DEFAULT = _("Default Bill-To")
ADDRESS_ID = _("Address ID")
STREET = _("Street")
BLOCK = _("Block")
BUILDING = _("Building")
CITY = _("City")
COUNTY = _("County / District")
ZIP_CODE = _("Zip Code")
COUNTRY = _("Country")
REGION = _("State / Region")
ADDRESS_TYPE = _("Address Type")
FROZEN = _("Frozen")

# --- SAP B1 parity: extra warehouse / item / document / finance / production ---
STREET_NO = _("Street No.")
FEDERAL_TAX_ID = _("Federal Tax ID")
DROP_SHIP = _("Drop Ship")
BIN_LOCATION_ACTIVE = _("Bin Locations Active")
WAREHOUSE_MASTER_LOCKED = _("Locked (warehouse)")
HANDWRITTEN = _("Handwritten")
PRINTED = _("Printed")
DOC_RATE = _("Exchange Rate")
ITEM_PICTURE = _("Picture")
WARRANTY_TEMPLATE = _("Warranty Template")
ITEM_WEIGHT = _("Weight")
ITEM_GROSS_WEIGHT = _("Gross Weight")
ITEM_VOLUME = _("Volume")
VAT_GROUP_SALES = _("VAT Group (Sales)")
VAT_GROUP_PURCHASE = _("VAT Group (Purchase)")
UOM_ENTRY_I = _("IUoM Entry")
UOM_ENTRY_P = _("PUoM Entry")
ITEM_GROUP_LOCKED = _("Locked (item group)")
LINE_DESCRIPTION = _("Description (line)")
OPEN_AMOUNT = _("Open Amount")
VISUAL_ORDER = _("Visual Order")
BOM_DISPLAY_NAME = _("BOM Display Name")
BOM_HEADER_LOCKED = _("Locked (BOM)")
ISSUE_METHOD = _("Issue Method")
LINE_TEXT = _("Line Text")
PRODUCTION_DUE_DATE = _("Due Date")
ORIGIN_TYPE = _("Origin Type")
ORIGIN_ENTRY = _("Origin Entry")
PROJECT_CODE = _("Project")
GL_LEVELS = _("Account Levels")
EXPORT_CODE = _("Export Code")
FIXED_ASSET_ACCOUNT = _("Fixed Asset Account")
CENTER_PARENT = _("Father Center")
JOURNAL_REF_1 = _("Reference 1")
JOURNAL_REF_2 = _("Reference 2")
LINE_REF_3 = _("Reference 3 (line)")
LINE_DUE_DATE = _("Due Date (line)")
LINE_MEMO = _("Line memo")
OCR_CODE = _("Offset Account")
TRANS_CODE = _("Transaction Code")
JOURNAL_DUE_DATE = _("Due Date (header)")
TRANSACTION_VALUE = _("Transaction value")
LINKED_DOC_ENTRY = _("Linked document entry")
LINKED_DOC_LINE = _("Linked document line")
PAYMENT_DOC_STATUS = _("Document Status")
TRANSFER_ACCOUNT = _("Transfer Account")
CHECK_SUM = _("Check Amount")
