# Generated by Django 6.0.4 on 2026-05-02 20:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPCH',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
                ('DocDate', models.DateField(db_index=True)),
                ('DocTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('VatSum', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
            ],
            options={
                'verbose_name': 'A/P invoice',
                'verbose_name_plural': 'A/P invoices',
                'db_table': 'OPCH',
            },
        ),
        migrations.CreateModel(
            name='OPDN',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
                ('DocDate', models.DateField(db_index=True)),
                ('DocStatus', models.CharField(db_index=True, default='O', max_length=1)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
            ],
            options={
                'verbose_name': 'Goods receipt PO',
                'verbose_name_plural': 'Goods receipt POs',
                'db_table': 'OPDN',
            },
        ),
        migrations.CreateModel(
            name='OPOR',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
                ('DocStatus', models.CharField(db_index=True, default='O', max_length=1)),
                ('DocDate', models.DateField(db_index=True)),
                ('DocTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
                'db_table': 'OPOR',
            },
        ),
        migrations.CreateModel(
            name='OPRQ',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('DocStatus', models.CharField(db_index=True, default='O', max_length=1)),
                ('Requester', models.CharField(db_index=True, max_length=200)),
                ('DocDate', models.DateField(db_index=True)),
                ('DocDueDate', models.DateField(db_index=True)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
            ],
            options={
                'verbose_name': 'Purchase request',
                'verbose_name_plural': 'Purchase requests',
                'db_table': 'OPRQ',
            },
        ),
        migrations.CreateModel(
            name='ORPC',
            fields=[
                ('DocEntry', models.BigAutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('CardCode', models.CharField(db_index=True, max_length=15)),
                ('CardName', models.CharField(blank=True, default='', max_length=200)),
                ('DocDate', models.DateField(db_index=True)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
            ],
            options={
                'verbose_name': 'Goods return (vendor)',
                'verbose_name_plural': 'Goods returns (vendor)',
                'db_table': 'ORPC',
            },
        ),
        migrations.CreateModel(
            name='PCH1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('LineTotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.opch')),
            ],
            options={
                'verbose_name': 'A/P invoice line',
                'verbose_name_plural': 'A/P invoice lines',
                'db_table': 'PCH1',
                'indexes': [models.Index(fields=['ItemCode'], name='pch1_itemcode_ix')],
            },
        ),
        migrations.CreateModel(
            name='PDN1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseLine', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.opdn')),
            ],
            options={
                'verbose_name': 'GRPO line',
                'verbose_name_plural': 'GRPO lines',
                'db_table': 'PDN1',
                'indexes': [models.Index(fields=['ItemCode'], name='pdn1_itemcode_ix'), models.Index(fields=['WhsCode'], name='pdn1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='POR1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseLine', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.opor')),
            ],
            options={
                'verbose_name': 'Purchase order line',
                'verbose_name_plural': 'Purchase order lines',
                'db_table': 'POR1',
                'indexes': [models.Index(fields=['ItemCode'], name='por1_itemcode_ix'), models.Index(fields=['WhsCode'], name='por1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='PRQ1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Dscription', models.CharField(blank=True, default='', max_length=200)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('LineStatus', models.CharField(db_index=True, default='O', max_length=1)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.oprq')),
            ],
            options={
                'verbose_name': 'Purchase request line',
                'verbose_name_plural': 'Purchase request lines',
                'db_table': 'PRQ1',
                'indexes': [models.Index(fields=['ItemCode'], name='prq1_itemcode_ix'), models.Index(fields=['WhsCode'], name='prq1_whscode_ix')],
            },
        ),
        migrations.CreateModel(
            name='RPC1',
            fields=[
                ('pk', models.CompositePrimaryKey('header', 'LineNum', blank=True, editable=False, primary_key=True, serialize=False)),
                ('LineNum', models.IntegerField()),
                ('ItemCode', models.CharField(db_index=True, max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('Price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('WhsCode', models.CharField(db_index=True, max_length=20)),
                ('BaseType', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseEntry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('BaseLine', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Canceled', models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled (Y/N)')),
                ('header', models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.orpc')),
            ],
            options={
                'verbose_name': 'Goods return line',
                'verbose_name_plural': 'Goods return lines',
                'db_table': 'RPC1',
                'indexes': [models.Index(fields=['ItemCode'], name='rpc1_itemcode_ix'), models.Index(fields=['WhsCode'], name='rpc1_whscode_ix')],
            },
        ),
    ]
