# Generated by Django 5.2.13 on 2026-05-02 21:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opch',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='opch',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='opch',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='opch',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='opch',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='opch',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='opch',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AlterField(
            model_name='opch',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='opdn',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='opdn',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='opdn',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='opdn',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='opdn',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='opdn',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='opdn',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='opor',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='opor',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='opor',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='opor',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='opor',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='opor',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='opor',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='opor',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AlterField(
            model_name='oprq',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='oprq',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='oprq',
            name='DocDueDate',
            field=models.DateField(db_index=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='oprq',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='oprq',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='oprq',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='oprq',
            name='Requester',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Requester'),
        ),
        migrations.AlterField(
            model_name='orpc',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='orpc',
            name='CardCode',
            field=models.CharField(db_index=True, max_length=15, verbose_name='BP Code'),
        ),
        migrations.AlterField(
            model_name='orpc',
            name='CardName',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='BP Name'),
        ),
        migrations.AlterField(
            model_name='orpc',
            name='DocDate',
            field=models.DateField(db_index=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='orpc',
            name='DocEntry',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Internal No.'),
        ),
        migrations.AlterField(
            model_name='orpc',
            name='DocNum',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='pch1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.opch', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='pdn1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.opdn', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='por1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.opor', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='LineStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Line Status'),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.oprq', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='BaseEntry',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Entry'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='BaseType',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Type'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='Canceled',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='ItemCode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='LineNum',
            field=models.IntegerField(verbose_name='Line No.'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='Quantity',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='WhsCode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='rpc1',
            name='header',
            field=models.ForeignKey(db_column='DocEntry', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_purchase.orpc', verbose_name='Document'),
        ),
    ]
