# Generated by Django 6.0.4 on 2026-05-02 23:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_purchase', '0002_alter_opch_canceled_alter_opch_cardcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opch',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='opch',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='opch',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='opch',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='opch',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='opch',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='opch',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='opch',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='opch',
            name='JrnlMemo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='opch',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='opch',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='opch',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='opch',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='opch',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='JrnlMemo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='opdn',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='opor',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='opor',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='opor',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='opor',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='opor',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='opor',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='opor',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='opor',
            name='JrnlMemo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='opor',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='opor',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='opor',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='opor',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='opor',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='opor',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='JrnlMemo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='oprq',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='CntctPrsn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='Comments',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='DiscSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Total'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='DocCur',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='DocDueDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='DocRate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='DocStatus',
            field=models.CharField(db_index=True, default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='DocTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Document Total'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='Handwrtten',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Handwritten'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='JrnlMemo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='NumAtCard',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BP Reference No.'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='OwnerCode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='Printed',
            field=models.CharField(db_index=True, default='N', max_length=1, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='SlpCode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sales Employee'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='TaxDate',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='orpc',
            name='VatSum',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='pch1',
            name='BaseLine',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Base Row'),
        ),
        migrations.AddField(
            model_name='pch1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='pch1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='pch1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='pch1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AddField(
            model_name='pch1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Purchase)'),
        ),
        migrations.AddField(
            model_name='pdn1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='pdn1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='pdn1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='pdn1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='pdn1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AddField(
            model_name='pdn1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Purchase)'),
        ),
        migrations.AddField(
            model_name='por1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='por1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='por1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='por1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='por1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AddField(
            model_name='por1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Purchase)'),
        ),
        migrations.AddField(
            model_name='prq1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='prq1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='prq1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='prq1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AddField(
            model_name='prq1',
            name='Price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, verbose_name='Unit Price'),
        ),
        migrations.AddField(
            model_name='prq1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Purchase)'),
        ),
        migrations.AddField(
            model_name='rpc1',
            name='Currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='rpc1',
            name='DiscPrcnt',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='rpc1',
            name='Dscription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description (line)'),
        ),
        migrations.AddField(
            model_name='rpc1',
            name='LineTotal',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='rpc1',
            name='OpenQty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Open Quantity'),
        ),
        migrations.AddField(
            model_name='rpc1',
            name='VatGroup',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='VAT Group (Purchase)'),
        ),
    ]
