import type { InvRegistryEntry } from "../inventory/registry";
import { FINANCE_API_ROOT } from "./constants";

function enc(s: string): string {
  return encodeURIComponent(s);
}

/** Bolt-backed finance masters / documents (``/api/finance``). */
export const FINANCE_BOLT_REGISTRY: InvRegistryEntry[] = [
  {
    id: "chart-of-accounts",
    title: "Chart of Accounts — OACT",
    listPath: `${FINANCE_API_ROOT}/chart-of-accounts`,
    detailPath: (r) => `${FINANCE_API_ROOT}/chart-of-accounts/${enc(String(r.AcctCode ?? "").trim())}`,
    pkKeys: ["AcctCode"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    listColumns: [
      { key: "AcctCode", label: "Acct Code" },
      { key: "AcctName", label: "Name" },
      { key: "GroupMask", label: "Type" },
      { key: "CurrTotal", label: "Balance" },
      { key: "Postable", label: "Post." },
    ],
    headerFields: [
      { key: "AcctCode", label: "G/L Account", kind: "text", pk: true },
      { key: "AcctName", label: "Account Name", kind: "text" },
      { key: "CurrTotal", label: "Balance", kind: "text" },
      { key: "GroupMask", label: "Group Mask (1–5)", kind: "number" },
      { key: "FatherNum", label: "Father Account", kind: "text" },
      { key: "Postable", label: "Posting (Y/N)", kind: "text" },
      { key: "LocCash", label: "Cash Account (Y/N)", kind: "text" },
      { key: "U_UserFld1", label: "User-defined field 1", kind: "text" },
      { key: "U_UserFld2", label: "User-defined field 2", kind: "text" },
    ],
    createKeys: ["AcctCode", "AcctName", "CurrTotal", "GroupMask", "FatherNum", "Postable", "LocCash", "U_UserFld1", "U_UserFld2"],
    patchKeys: ["AcctName", "CurrTotal", "GroupMask", "FatherNum", "Postable", "LocCash", "U_UserFld1", "U_UserFld2"],
  },
  {
    id: "profit-centers",
    title: "Profit / Cost Centers — OPRC",
    listPath: `${FINANCE_API_ROOT}/profit-centers`,
    detailPath: (r) => `${FINANCE_API_ROOT}/profit-centers/${enc(String(r.PrcCode ?? "").trim())}`,
    pkKeys: ["PrcCode"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    listColumns: [
      { key: "PrcCode", label: "Center" },
      { key: "PrcName", label: "Name" },
      { key: "DimCode", label: "Dim" },
      { key: "Active", label: "Active" },
    ],
    headerFields: [
      { key: "PrcCode", label: "Profit Center", kind: "text", pk: true },
      { key: "PrcName", label: "Name", kind: "text" },
      { key: "DimCode", label: "Dimension (1–5)", kind: "number" },
      { key: "Active", label: "Active (Y/N)", kind: "text" },
      { key: "U_UserFld1", label: "User-defined field 1", kind: "text" },
      { key: "U_UserFld2", label: "User-defined field 2", kind: "text" },
    ],
    createKeys: ["PrcCode", "PrcName", "DimCode", "Active", "U_UserFld1", "U_UserFld2"],
    patchKeys: ["PrcName", "DimCode", "Active", "U_UserFld1", "U_UserFld2"],
  },
  {
    id: "tax-codes",
    title: "Tax Codes — OSTC",
    listPath: `${FINANCE_API_ROOT}/tax-codes`,
    detailPath: (r) => `${FINANCE_API_ROOT}/tax-codes/${enc(String(r.Code ?? "").trim())}`,
    pkKeys: ["Code"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    listColumns: [
      { key: "Code", label: "Code" },
      { key: "Name", label: "Name" },
      { key: "Rate", label: "Rate %" },
      { key: "Account", label: "Tax G/L" },
    ],
    headerFields: [
      { key: "Code", label: "Tax Code", kind: "text", pk: true },
      { key: "Name", label: "Name", kind: "text" },
      { key: "Rate", label: "Rate", kind: "text" },
      { key: "Account", label: "Tax Account", kind: "text" },
    ],
    createKeys: ["Code", "Name", "Rate", "Account"],
    patchKeys: ["Name", "Rate", "Account"],
  },
  {
    id: "financial-periods",
    title: "Financial Periods — OFPR",
    listPath: `${FINANCE_API_ROOT}/financial-periods`,
    detailPath: (r) => `${FINANCE_API_ROOT}/financial-periods/${Number(r.AbsEntry)}`,
    pkKeys: ["AbsEntry"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    keepDetailAfterCreate: true,
    listColumns: [
      { key: "AbsEntry", label: "Entry" },
      { key: "PeriodCode", label: "Code" },
      { key: "F_RefDate", label: "From" },
      { key: "T_RefDate", label: "To" },
      { key: "PeriodStat", label: "Status" },
    ],
    headerFields: [
      { key: "AbsEntry", label: "Internal No.", kind: "number", pk: true },
      { key: "PeriodCode", label: "Period Code", kind: "text" },
      { key: "F_RefDate", label: "Period From", kind: "date" },
      { key: "T_RefDate", label: "Period To", kind: "date" },
      { key: "PeriodStat", label: "Status", kind: "text" },
    ],
    createKeys: ["PeriodCode", "F_RefDate", "T_RefDate", "PeriodStat"],
    patchKeys: ["PeriodCode", "F_RefDate", "T_RefDate", "PeriodStat"],
  },
  {
    id: "journal-entries",
    title: "Journal Entries — OJDT",
    listPath: `${FINANCE_API_ROOT}/journal-entries`,
    detailPath: (r) => `${FINANCE_API_ROOT}/journal-entries/${Number(r.TransId)}`,
    pkKeys: ["TransId"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    keepDetailAfterCreate: true,
    listColumns: [
      { key: "TransId", label: "TransId" },
      { key: "RefDate", label: "Date" },
      { key: "TransType", label: "Type" },
      { key: "BaseRef", label: "Reference" },
    ],
    headerFields: [
      { key: "TransId", label: "TransId", kind: "number", pk: true },
      { key: "BaseRef", label: "Reference", kind: "text" },
      { key: "RefDate", label: "Posting Date", kind: "date" },
      { key: "TransType", label: "Transaction Type", kind: "number" },
      { key: "Memo", label: "Memo", kind: "text" },
      { key: "U_UserFld1", label: "User-defined field 1", kind: "text" },
      { key: "U_UserFld2", label: "User-defined field 2", kind: "text" },
    ],
    createKeys: ["BaseRef", "RefDate", "TransType", "Memo", "U_UserFld1", "U_UserFld2"],
    patchKeys: ["BaseRef", "RefDate", "TransType", "Memo", "U_UserFld1", "U_UserFld2"],
  },
  {
    id: "incoming-payments",
    title: "Incoming Payments — ORCT",
    listPath: `${FINANCE_API_ROOT}/incoming-payments`,
    detailPath: (r) => `${FINANCE_API_ROOT}/incoming-payments/${Number(r.DocEntry)}`,
    pkKeys: ["DocEntry"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    keepDetailAfterCreate: true,
    listColumns: [
      { key: "DocEntry", label: "DocEntry" },
      { key: "CardCode", label: "BP" },
      { key: "DocDate", label: "Date" },
      { key: "DocTotal", label: "Total" },
    ],
    headerFields: [
      { key: "DocEntry", label: "DocEntry", kind: "number", pk: true },
      { key: "CardCode", label: "Card Code", kind: "text" },
      { key: "CardName", label: "Card Name", kind: "text" },
      { key: "DocDate", label: "Doc Date", kind: "date" },
      { key: "CashAcct", label: "Cash Account", kind: "text" },
      { key: "CheckAcct", label: "Check Account", kind: "text" },
      { key: "DocTotal", label: "Doc Total", kind: "text" },
      { key: "CashSum", label: "Cash Sum", kind: "text" },
      { key: "DocStatus", label: "Status (O/C)", kind: "text" },
      { key: "U_UserFld1", label: "User-defined field 1", kind: "text" },
      { key: "U_UserFld2", label: "User-defined field 2", kind: "text" },
    ],
    createKeys: ["CardCode", "CardName", "DocDate", "CashAcct", "CheckAcct", "DocTotal", "CashSum", "U_UserFld1", "U_UserFld2"],
    patchKeys: ["CardCode", "CardName", "DocDate", "CashAcct", "CheckAcct", "DocTotal", "CashSum", "DocStatus", "U_UserFld1", "U_UserFld2"],
  },
  {
    id: "outgoing-payments",
    title: "Outgoing Payments — OVPM",
    listPath: `${FINANCE_API_ROOT}/outgoing-payments`,
    detailPath: (r) => `${FINANCE_API_ROOT}/outgoing-payments/${Number(r.DocEntry)}`,
    pkKeys: ["DocEntry"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    keepDetailAfterCreate: true,
    listColumns: [
      { key: "DocEntry", label: "DocEntry" },
      { key: "CardCode", label: "BP" },
      { key: "DocDate", label: "Date" },
      { key: "DocTotal", label: "Total" },
    ],
    headerFields: [
      { key: "DocEntry", label: "DocEntry", kind: "number", pk: true },
      { key: "CardCode", label: "Card Code", kind: "text" },
      { key: "CardName", label: "Card Name", kind: "text" },
      { key: "DocDate", label: "Doc Date", kind: "date" },
      { key: "BankAcct", label: "Bank Account", kind: "text" },
      { key: "CashSum", label: "Cash Sum", kind: "text" },
      { key: "TrsfrSum", label: "Transfer Sum", kind: "text" },
      { key: "DocTotal", label: "Doc Total", kind: "text" },
      { key: "DocStatus", label: "Status (O/C)", kind: "text" },
      { key: "U_UserFld1", label: "User-defined field 1", kind: "text" },
      { key: "U_UserFld2", label: "User-defined field 2", kind: "text" },
    ],
    createKeys: ["CardCode", "CardName", "DocDate", "BankAcct", "CashSum", "TrsfrSum", "DocTotal", "U_UserFld1", "U_UserFld2"],
    patchKeys: ["CardCode", "CardName", "DocDate", "BankAcct", "CashSum", "TrsfrSum", "DocTotal", "DocStatus", "U_UserFld1", "U_UserFld2"],
  },
  {
    id: "budget-setups",
    title: "Budget Setup — OBGT",
    listPath: `${FINANCE_API_ROOT}/budget-setups`,
    detailPath: (r) => `${FINANCE_API_ROOT}/budget-setups/${enc(String(r.AcctCode ?? "").trim())}`,
    pkKeys: ["AcctCode"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    listColumns: [
      { key: "AcctCode", label: "G/L" },
      { key: "BudgTotal", label: "Budget Total" },
    ],
    headerFields: [
      { key: "AcctCode", label: "G/L Account", kind: "text", pk: true },
      { key: "BudgTotal", label: "Budget Total", kind: "text" },
    ],
    createKeys: ["AcctCode", "BudgTotal"],
    patchKeys: ["BudgTotal"],
  },
  {
    id: "jdt1-lines",
    title: "Journal Entry Lines — JDT1",
    listPath: `${FINANCE_API_ROOT}/journal-entry-lines`,
    detailPath: (r) =>
      `${FINANCE_API_ROOT}/journal-entry-lines/${Number(r.TransId)}/${Number(r.Line_ID)}`,
    pkKeys: ["TransId", "Line_ID"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    listColumns: [
      { key: "TransId", label: "TransId" },
      { key: "Line_ID", label: "Line" },
      { key: "Account", label: "G/L" },
      { key: "Debit", label: "Debit" },
      { key: "Credit", label: "Credit" },
    ],
    headerFields: [
      { key: "TransId", label: "TransId (OJDT)", kind: "number", pk: true },
      { key: "Line_ID", label: "Line ID", kind: "number", pk: true },
      { key: "Account", label: "G/L Account", kind: "text" },
      { key: "ShortName", label: "Short Name", kind: "text" },
      { key: "Debit", label: "Debit", kind: "text" },
      { key: "Credit", label: "Credit", kind: "text" },
      { key: "ProfitCode", label: "Profit Center", kind: "text" },
    ],
    createKeys: ["TransId", "Line_ID", "Account", "ShortName", "Debit", "Credit", "ProfitCode"],
    patchKeys: ["Account", "ShortName", "Debit", "Credit", "ProfitCode"],
  },
  {
    id: "bgt1-lines",
    title: "Budget Lines — BGT1",
    listPath: `${FINANCE_API_ROOT}/budget-lines`,
    detailPath: (r) => {
      const acct = enc(String(r.AcctCode ?? "").trim());
      const month = Number(r.Month);
      const prc = String(r.PrcCode ?? "").trim();
      const prcSeg = prc === "" ? "-" : enc(prc);
      return `${FINANCE_API_ROOT}/budget-lines/${acct}/${month}/${prcSeg}`;
    },
    pkKeys: ["AcctCode", "Month", "PrcCode"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    listColumns: [
      { key: "AcctCode", label: "G/L" },
      { key: "Month", label: "M" },
      { key: "PrcCode", label: "Prc" },
      { key: "PlannedAmt", label: "Planned" },
    ],
    headerFields: [
      { key: "AcctCode", label: "G/L Account", kind: "text", pk: true },
      { key: "Month", label: "Month (1–12)", kind: "number", pk: true },
      { key: "PrcCode", label: "Profit Center (blank = \"-\")", kind: "text", pk: true },
      { key: "PlannedAmt", label: "Planned Amount", kind: "text" },
    ],
    createKeys: ["AcctCode", "Month", "PrcCode", "PlannedAmt"],
    patchKeys: ["PlannedAmt"],
  },
  {
    id: "rct1-lines",
    title: "Incoming Payment Lines — RCT1",
    listPath: `${FINANCE_API_ROOT}/incoming-payment-lines`,
    detailPath: (r) =>
      `${FINANCE_API_ROOT}/incoming-payment-lines/${Number(r.DocEntry)}/${Number(r.LineNum)}`,
    pkKeys: ["DocEntry", "LineNum"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    listColumns: [
      { key: "DocEntry", label: "Doc" },
      { key: "LineNum", label: "#" },
      { key: "DocNum", label: "Inv No." },
      { key: "SumApplied", label: "Applied" },
      { key: "InvType", label: "Type" },
    ],
    headerFields: [
      { key: "DocEntry", label: "ORCT DocEntry", kind: "number", pk: true },
      { key: "LineNum", label: "Line Num", kind: "number", pk: true },
      { key: "DocNum", label: "Invoice DocNum", kind: "number" },
      { key: "SumApplied", label: "Sum Applied", kind: "text" },
      { key: "InvType", label: "Invoice Type", kind: "number" },
    ],
    createKeys: ["DocEntry", "LineNum", "DocNum", "SumApplied", "InvType"],
    patchKeys: ["DocNum", "SumApplied", "InvType"],
  },
  {
    id: "vpm1-lines",
    title: "Outgoing Payment Lines — VPM1",
    listPath: `${FINANCE_API_ROOT}/outgoing-payment-lines`,
    detailPath: (r) =>
      `${FINANCE_API_ROOT}/outgoing-payment-lines/${Number(r.DocEntry)}/${Number(r.LineNum)}`,
    pkKeys: ["DocEntry", "LineNum"],
    formFirstListOnFind: true,
    readonlyEnv: "finance",
    listColumns: [
      { key: "DocEntry", label: "Doc" },
      { key: "LineNum", label: "#" },
      { key: "DocNum", label: "Inv No." },
      { key: "SumApplied", label: "Applied" },
      { key: "InvType", label: "Type" },
    ],
    headerFields: [
      { key: "DocEntry", label: "OVPM DocEntry", kind: "number", pk: true },
      { key: "LineNum", label: "Line Num", kind: "number", pk: true },
      { key: "DocNum", label: "Invoice DocNum", kind: "number" },
      { key: "SumApplied", label: "Sum Applied", kind: "text" },
      { key: "InvType", label: "Invoice Type", kind: "number" },
    ],
    createKeys: ["DocEntry", "LineNum", "DocNum", "SumApplied", "InvType"],
    patchKeys: ["DocNum", "SumApplied", "InvType"],
  },
];
